"""Independent spatiotemporal DVRP instance generator.

This module deliberately lives beside, rather than inside, the existing
``svrp_generator.py`` implementation.  It reuses the original generator for
locations, demands, service times, depots, and fleet sizing, while replacing
the residential/commercial time-window model and the independent dynamic-node
selection with a joint temporal-spatial construction.

The construction factorises dynamic arrivals as

    P(release_time, cluster)
      = P(release_time) P(cluster | release_period).

``temporal_mode`` controls the first term (uniform, bursty, or a
reality-calibrated burst profile), and
``spatial_mode`` controls whether the second term is stationary or varies by
release period.  Customer coordinates and their original Gaussian-cluster
labels are never regenerated by the hotspot logic.
"""

from __future__ import annotations

import argparse
import json
import os
from typing import List, Optional, Sequence

import numpy as np

try:
    from .svrp_generator import SVRPGenerator as BaseSVRPGenerator
except ImportError:
    from svrp_generator import SVRPGenerator as BaseSVRPGenerator


class ImmediateReachabilityError(RuntimeError):
    """Raised when an order is unreachable even under immediate dispatch."""


class SpatioTemporalSVRPGenerator(BaseSVRPGenerator):
    """Generate DVRP instances with independent temporal and spatial regimes."""

    TEMPORAL_MODES = {"uniform", "bursty", "realistic_bursty"}
    SPATIAL_MODES = {"stationary", "time_varying"}
    BURST_PRESETS = {
        "bursty": {
            "name": "strong",
            "width": 15.0,
            "strength": 0.95,
        },
        "realistic_bursty": {
            "name": "reality_calibrated",
            # Compatibility fallbacks used only when callers explicitly turn
            # the empirical two-window profile into a custom generic mixture.
            "width": 30.0,
            "strength": 0.75,
            # Meituan--INFORMS calibration, expressed on the default
            # 00:00--20:00 release clock (1200 minutes).  The two empirical
            # windows contain about 29.92% and 21.22% of daily orders.
            "peak_names": ("lunch", "dinner"),
            "peak_windows": ((645.0, 780.0), (1020.0, 1140.0)),
            "center_ranges": ((675.0, 735.0), (1050.0, 1110.0)),
            # These wider, unequal kernels reproduce the observed 30/60-minute
            # mass after conditioning each component on its empirical window.
            # Lunch stays sharper; dinner is deliberately broader.
            "width_ranges": ((50.0, 60.0), (60.0, 75.0)),
            "share_ranges": ((0.28, 0.32), (0.19, 0.23)),
            "reference_release_horizon": 1200.0,
        },
    }

    @staticmethod
    def _normalize_range(
        values: Optional[Sequence[float]], name: str
    ) -> Optional[tuple[float, float]]:
        if values is None:
            return None
        if len(values) != 2:
            raise ValueError(f"{name} must contain exactly two values: min,max.")
        low, high = (float(values[0]), float(values[1]))
        if low > high:
            raise ValueError(f"{name} must satisfy min <= max.")
        return low, high

    def __init__(
        self,
        num_customers: int = 100,
        map_size: int = 1000,
        dod: float = 0.5,
        fixed_vehicle_num: Optional[int] = None,
        fixed_vehicle_capacity: Optional[int] = None,
        depot_type: str = "single",
        depot_placement: str = "center",
        service_time_mode: str = "linear",
        seed: Optional[int] = None,
        verbose: bool = False,
        temporal_mode: str = "uniform",
        spatial_mode: str = "stationary",
        horizon: int = 1440,
        release_horizon: Optional[int] = None,
        reaction_buffer: int = 30,
        lead_time_min: int = 30,
        lead_time_max: int = 120,
        tw_width_min: int = 60,
        tw_width_max: int = 120,
        burst_count: Optional[int] = None,
        burst_centers: Optional[Sequence[int]] = None,
        burst_width: Optional[float] = None,
        burst_strength: Optional[float] = None,
        spatial_period_count: int = 4,
        hotspot_strength: float = 0.80,
        hotspot_clusters_per_period: Optional[int] = None,
        hotspot_schedule: Optional[Sequence[Sequence[int]]] = None,
        stationary_cluster_weights: Optional[Sequence[float]] = None,
        burst_width_range: Optional[Sequence[float]] = None,
        burst_strength_range: Optional[Sequence[float]] = None,
        feasibility_vehicle_speed: float = 5.0,
    ):
        super().__init__(
            num_customers=num_customers,
            map_size=map_size,
            dod=dod,
            fixed_vehicle_num=fixed_vehicle_num,
            fixed_vehicle_capacity=fixed_vehicle_capacity,
            depot_type=depot_type,
            depot_placement=depot_placement,
            service_time_mode=service_time_mode,
            seed=seed,
            verbose=verbose,
        )

        self.seed = seed
        self.rng = np.random.default_rng(seed)
        # Keep hotspot grouping random but independent from the temporal RNG.
        # This preserves paired Uniform/Bursty release profiles when only the
        # spatial regime changes.
        schedule_seed = (
            None
            if seed is None
            else np.random.SeedSequence([int(seed), 0x484F5453])
        )
        self.hotspot_rng = np.random.default_rng(schedule_seed)
        self.temporal_mode = temporal_mode.replace("-", "_").lower()
        self.spatial_mode = spatial_mode.replace("-", "_").lower()
        self.horizon = int(horizon)
        self.reaction_buffer = int(reaction_buffer)
        self.lead_time_min = int(lead_time_min)
        self.lead_time_max = int(lead_time_max)
        self.tw_width_min = int(tw_width_min)
        self.tw_width_max = int(tw_width_max)
        self.burst_count = burst_count
        self.requested_burst_centers = (
            None if burst_centers is None else [int(x) for x in burst_centers]
        )
        burst_preset = self.BURST_PRESETS.get(
            self.temporal_mode, self.BURST_PRESETS["bursty"]
        )
        if burst_width is not None and burst_width_range is not None:
            raise ValueError("Specify burst_width or burst_width_range, not both.")
        if burst_strength is not None and burst_strength_range is not None:
            raise ValueError(
                "Specify burst_strength or burst_strength_range, not both."
            )
        explicit_width_range = self._normalize_range(
            burst_width_range, "burst_width_range"
        )
        explicit_strength_range = self._normalize_range(
            burst_strength_range, "burst_strength_range"
        )
        uses_mode_default = all(
            value is None
            for value in (
                burst_width,
                burst_strength,
                explicit_width_range,
                explicit_strength_range,
                burst_count,
                self.requested_burst_centers,
            )
        )
        self.realistic_calendar_profile = (
            self.temporal_mode == "realistic_bursty" and uses_mode_default
        )
        if self.temporal_mode == "uniform":
            self.burst_profile = "none"
        elif uses_mode_default:
            self.burst_profile = str(burst_preset["name"])
        else:
            self.burst_profile = "custom"

        default_width_range = self._normalize_range(
            burst_preset.get("width_range"), "preset width_range"
        )
        default_strength_range = self._normalize_range(
            burst_preset.get("strength_range"), "preset strength_range"
        )
        self.burst_width_sampling_range = (
            explicit_width_range
            if explicit_width_range is not None
            else default_width_range if burst_width is None else None
        )
        self.burst_strength_sampling_range = (
            explicit_strength_range
            if explicit_strength_range is not None
            else default_strength_range if burst_strength is None else None
        )
        if self.realistic_calendar_profile:
            self.realistic_peak_names = list(burst_preset["peak_names"])
            self.realistic_peak_windows_reference = [
                tuple(float(x) for x in bounds)
                for bounds in burst_preset["peak_windows"]
            ]
            self.realistic_center_ranges_reference = [
                tuple(float(x) for x in bounds)
                for bounds in burst_preset["center_ranges"]
            ]
            self.realistic_width_sampling_ranges = [
                tuple(float(x) for x in bounds)
                for bounds in burst_preset["width_ranges"]
            ]
            self.realistic_share_sampling_ranges = [
                tuple(float(x) for x in bounds)
                for bounds in burst_preset["share_ranges"]
            ]
            self.realistic_reference_release_horizon = float(
                burst_preset["reference_release_horizon"]
            )
            self.realized_burst_widths = [
                float(self.rng.uniform(*bounds))
                for bounds in self.realistic_width_sampling_ranges
            ]
            self.realized_burst_component_shares = [
                float(self.rng.uniform(*bounds))
                for bounds in self.realistic_share_sampling_ranges
            ]
            self.burst_width = float(np.mean(self.realized_burst_widths))
            self.burst_strength = float(
                np.sum(self.realized_burst_component_shares)
            )
        elif burst_width is not None:
            self.burst_width = float(burst_width)
        elif self.burst_width_sampling_range is not None:
            self.burst_width = float(
                self.rng.uniform(*self.burst_width_sampling_range)
            )
        else:
            self.burst_width = float(burst_preset["width"])
        if not self.realistic_calendar_profile:
            if burst_strength is not None:
                self.burst_strength = float(burst_strength)
            elif self.burst_strength_sampling_range is not None:
                self.burst_strength = float(
                    self.rng.uniform(*self.burst_strength_sampling_range)
                )
            else:
                self.burst_strength = float(burst_preset["strength"])

        self.burst_parameter_source = (
            "not_applicable"
            if self.temporal_mode == "uniform"
            else (
                "mode_default_randomized"
                if uses_mode_default and (
                    self.realistic_calendar_profile
                    or
                    self.burst_width_sampling_range is not None
                    or self.burst_strength_sampling_range is not None
                )
                else "mode_default_fixed"
                if uses_mode_default
                else "explicit_range"
                if explicit_width_range is not None
                or explicit_strength_range is not None
                else "explicit_override"
            )
        )
        self.spatial_period_count = int(spatial_period_count)
        self.hotspot_strength = float(hotspot_strength)
        self.hotspot_clusters_per_period = (
            None
            if hotspot_clusters_per_period is None
            else int(hotspot_clusters_per_period)
        )
        self.requested_hotspot_schedule = (
            None
            if hotspot_schedule is None
            else [[int(c) for c in period] for period in hotspot_schedule]
        )
        self.stationary_cluster_weights = (
            None
            if stationary_cluster_weights is None
            else np.asarray(stationary_cluster_weights, dtype=float)
        )
        self.feasibility_vehicle_speed = float(feasibility_vehicle_speed)

        latest_safe_release = (
            self.horizon - self.lead_time_max - self.tw_width_max
        )
        self.release_horizon = int(
            latest_safe_release if release_horizon is None else release_horizon
        )
        self._validate_configuration(latest_safe_release)

    def _validate_configuration(self, latest_safe_release: int) -> None:
        if self.n <= 0:
            raise ValueError("num_customers must be positive.")
        if not 0.0 <= self.dod <= 1.0:
            raise ValueError("dod must be in [0, 1].")
        if self.temporal_mode not in self.TEMPORAL_MODES:
            raise ValueError(
                f"temporal_mode must be one of {sorted(self.TEMPORAL_MODES)}."
            )
        if self.spatial_mode not in self.SPATIAL_MODES:
            raise ValueError(
                f"spatial_mode must be one of {sorted(self.SPATIAL_MODES)}."
            )
        if self.horizon <= 0:
            raise ValueError("horizon must be positive.")
        if self.reaction_buffer < 0:
            raise ValueError("reaction_buffer must be non-negative.")
        if self.feasibility_vehicle_speed <= 0:
            raise ValueError("feasibility_vehicle_speed must be positive.")
        if self.lead_time_min < self.reaction_buffer:
            raise ValueError(
                "lead_time_min must be at least reaction_buffer so that "
                "available_time <= tw_start - reaction_buffer."
            )
        if not 0 < self.lead_time_min <= self.lead_time_max:
            raise ValueError("lead-time bounds must satisfy 0 < min <= max.")
        if not 0 < self.tw_width_min <= self.tw_width_max:
            raise ValueError("time-window width bounds must satisfy 0 < min <= max.")
        if not 0 < self.release_horizon <= latest_safe_release:
            raise ValueError(
                "release_horizon must be positive and no larger than "
                "horizon - lead_time_max - tw_width_max "
                f"({latest_safe_release} with the current configuration)."
            )
        if self.burst_count is not None and int(self.burst_count) <= 0:
            raise ValueError("burst_count must be positive when specified.")
        if self.burst_width <= 0:
            raise ValueError("burst_width must be positive.")
        if (
            self.burst_width_sampling_range is not None
            and self.burst_width_sampling_range[0] <= 0
        ):
            raise ValueError("burst_width_range values must be positive.")
        if not 0.0 <= self.burst_strength <= 1.0:
            raise ValueError("burst_strength must be in [0, 1].")
        if (
            self.burst_strength_sampling_range is not None
            and (
                self.burst_strength_sampling_range[0] < 0.0
                or self.burst_strength_sampling_range[1] > 1.0
            )
        ):
            raise ValueError("burst_strength_range values must be in [0, 1].")
        if self.spatial_period_count <= 0:
            raise ValueError("spatial_period_count must be positive.")
        if not 0.0 <= self.hotspot_strength <= 1.0:
            raise ValueError("hotspot_strength must be in [0, 1].")
        if (
            self.hotspot_clusters_per_period is not None
            and self.hotspot_clusters_per_period <= 0
        ):
            raise ValueError("hotspot_clusters_per_period must be positive.")
        if (
            self.requested_hotspot_schedule is not None
            and len(self.requested_hotspot_schedule) != self.spatial_period_count
        ):
            raise ValueError(
                "hotspot_schedule must contain exactly spatial_period_count periods."
            )

    def generate_all(self):
        """Generate a complete instance without invoking the old TW logic."""
        self.generate_locations()
        self.generate_demands()
        self.generate_service_times()
        self.calculate_fleet()
        self.generate_spatiotemporal_attributes()
        return self

    def _round_release_times(self, values: np.ndarray, dynamic: bool) -> np.ndarray:
        """Round sampled releases to integer minutes without epoch alignment."""
        values = np.asarray(values, dtype=float)
        values = np.rint(values)
        lower = 1 if dynamic else 0
        values = np.clip(values, lower, self.release_horizon)
        return values.astype(int)

    def _resolve_burst_centers(self, profile_count: int) -> List[int]:
        if self.requested_burst_centers is not None:
            centers = np.asarray(self.requested_burst_centers, dtype=float)
        elif self.realistic_calendar_profile:
            scale = (
                self.release_horizon / self.realistic_reference_release_horizon
            )
            centers = np.asarray(
                [
                    self.rng.uniform(low * scale, high * scale)
                    for low, high in self.realistic_center_ranges_reference
                ],
                dtype=float,
            )
        else:
            if self.burst_count is None:
                count = 4
            else:
                count = int(self.burst_count)

            segment = self.release_horizon / (count + 1)
            base = np.linspace(segment, self.release_horizon - segment, count)
            jitter = self.rng.normal(0.0, 0.15 * segment, size=count)
            centers = base + jitter

        centers = self._round_release_times(centers, dynamic=True)
        centers = np.unique(centers)
        if len(centers) == 0:
            centers = np.asarray([max(1, self.release_horizon // 2)], dtype=int)
        return [int(x) for x in centers]

    def _scaled_realistic_peak_windows(self) -> List[tuple[float, float]]:
        scale = self.release_horizon / self.realistic_reference_release_horizon
        return [
            (low * scale, high * scale)
            for low, high in self.realistic_peak_windows_reference
        ]

    def _sample_truncated_normal(
        self,
        count: int,
        center: float,
        width: float,
        lower: float,
        upper: float,
    ) -> np.ndarray:
        """Sample a normal component without leaking outside its peak window."""
        if count <= 0:
            return np.asarray([], dtype=float)
        accepted: List[float] = []
        while len(accepted) < count:
            draw_count = max(16, 2 * (count - len(accepted)))
            draws = self.rng.normal(center, width, size=draw_count)
            accepted.extend(
                float(x) for x in draws if lower <= float(x) <= upper
            )
        return np.asarray(accepted[:count], dtype=float)

    def _sample_uniform_outside_windows(
        self,
        count: int,
        low: float,
        windows: Sequence[tuple[float, float]],
    ) -> np.ndarray:
        """Sample the empirical off-peak background over non-peak intervals."""
        if count <= 0:
            return np.asarray([], dtype=float)
        intervals: List[tuple[float, float]] = []
        cursor = low
        for window_low, window_high in sorted(windows):
            if window_low > cursor:
                intervals.append((cursor, window_low))
            cursor = max(cursor, window_high)
        if cursor < self.release_horizon:
            intervals.append((cursor, float(self.release_horizon)))
        lengths = np.asarray([high - lower for lower, high in intervals])
        probabilities = lengths / np.sum(lengths)
        interval_ids = self.rng.choice(
            len(intervals), size=count, replace=True, p=probabilities
        )
        return np.asarray(
            [
                self.rng.uniform(*intervals[int(interval_id)])
                for interval_id in interval_ids
            ],
            dtype=float,
        )

    def _sample_realistic_release_times(
        self, count: int, dynamic: bool
    ) -> np.ndarray:
        """Sample the calibrated lunch/dinner profile and off-peak background."""
        low = 1.0 if dynamic else 0.0
        peak_windows = self._scaled_realistic_peak_windows()
        probabilities = np.asarray(
            [
                1.0 - self.burst_strength,
                *self.realized_burst_component_shares,
            ],
            dtype=float,
        )
        probabilities = probabilities / probabilities.sum()
        component_counts = self.rng.multinomial(count, probabilities)
        samples = [
            self._sample_uniform_outside_windows(
                int(component_counts[0]), low, peak_windows
            )
        ]
        for component_id, ((window_low, window_high), center, width) in enumerate(
            zip(
                peak_windows,
                self.realized_burst_centers,
                self.realized_burst_widths,
            ),
            start=1,
        ):
            samples.append(
                self._sample_truncated_normal(
                    int(component_counts[component_id]),
                    float(center),
                    float(width),
                    max(low, window_low),
                    window_high,
                )
            )
        raw = np.concatenate(samples)
        self.rng.shuffle(raw)
        return self._round_release_times(raw, dynamic=dynamic)

    def _sample_release_times(self, count: int, dynamic: bool) -> np.ndarray:
        if count <= 0:
            return np.asarray([], dtype=int)

        low = 1.0 if dynamic else 0.0
        if self.temporal_mode == "uniform":
            raw = self.rng.uniform(low, self.release_horizon, size=count)
        elif self.realistic_calendar_profile:
            return self._sample_realistic_release_times(count, dynamic)
        else:
            use_burst = self.rng.random(count) < self.burst_strength
            raw = self.rng.uniform(low, self.release_horizon, size=count)
            if np.any(use_burst):
                chosen_centers = self.rng.choice(
                    np.asarray(self.realized_burst_centers),
                    size=int(np.sum(use_burst)),
                    replace=True,
                )
                raw[use_burst] = self.rng.normal(
                    chosen_centers, self.burst_width
                )
        return self._round_release_times(raw, dynamic=dynamic)

    def _resolve_hotspot_schedule(self, num_clusters: int) -> List[List[int]]:
        if self.requested_hotspot_schedule is not None:
            schedule = self.requested_hotspot_schedule
            self.hotspot_schedule_policy = "explicit"
        elif self.hotspot_clusters_per_period is not None:
            active_count = min(self.hotspot_clusters_per_period, num_clusters)
            schedule = [
                sorted(
                    int(cluster_id)
                    for cluster_id in self.hotspot_rng.choice(
                        num_clusters,
                        size=active_count,
                        replace=False,
                    )
                )
                for _ in range(self.spatial_period_count)
            ]
            self.hotspot_schedule_policy = "fixed_count_random"
        else:
            # Randomly partition all clusters across periods. When there are at
            # least as many clusters as periods, every cluster is active in
            # exactly one period and group sizes differ by at most one. Thus
            # 10 clusters over 4 periods produce a random 3/3/2/2 schedule.
            cluster_order = [
                int(cluster_id)
                for cluster_id in self.hotspot_rng.permutation(num_clusters)
            ]
            if num_clusters >= self.spatial_period_count:
                base_count, remainder = divmod(
                    num_clusters, self.spatial_period_count
                )
                period_counts = [
                    base_count + (1 if period < remainder else 0)
                    for period in range(self.spatial_period_count)
                ]
                self.hotspot_rng.shuffle(period_counts)
                schedule = []
                cursor = 0
                for active_count in period_counts:
                    schedule.append(
                        sorted(cluster_order[cursor : cursor + active_count])
                    )
                    cursor += active_count
            else:
                # No period may be empty. Reuse clusters only when the number
                # of periods exceeds the number of available clusters.
                schedule = [
                    [cluster_order[period % num_clusters]]
                    for period in range(self.spatial_period_count)
                ]
            self.hotspot_schedule_policy = "balanced_random"

        checked = []
        for period, active_clusters in enumerate(schedule):
            if not active_clusters:
                raise ValueError(f"Hotspot period {period} has no active cluster.")
            unique_clusters = list(dict.fromkeys(int(c) for c in active_clusters))
            invalid = [c for c in unique_clusters if c < 0 or c >= num_clusters]
            if invalid:
                raise ValueError(
                    f"Hotspot period {period} references invalid clusters {invalid}; "
                    f"valid cluster IDs are 0..{num_clusters - 1}."
                )
            checked.append(unique_clusters)
        return checked

    def _period_of(self, release_time: int) -> int:
        period = int(
            np.searchsorted(
                self.period_boundaries[1:], release_time, side="right"
            )
        )
        return int(np.clip(period, 0, self.spatial_period_count - 1))

    def _stationary_weights(self, cluster_sizes: np.ndarray) -> np.ndarray:
        if self.stationary_cluster_weights is None:
            weights = cluster_sizes.astype(float)
        else:
            if len(self.stationary_cluster_weights) != len(cluster_sizes):
                raise ValueError(
                    "stationary_cluster_weights must have one value per original "
                    f"spatial cluster ({len(cluster_sizes)} values required)."
                )
            if np.any(self.stationary_cluster_weights < 0):
                raise ValueError("stationary_cluster_weights cannot be negative.")
            weights = self.stationary_cluster_weights.astype(float)
        if weights.sum() <= 0:
            raise ValueError("At least one stationary cluster weight must be positive.")
        return weights / weights.sum()

    def _cluster_distribution(
        self,
        period: int,
        base_distribution: np.ndarray,
        stationary_distribution: np.ndarray,
    ) -> np.ndarray:
        if self.spatial_mode == "stationary":
            return stationary_distribution.copy()

        active = self.hotspot_schedule[period]
        hotspot_distribution = np.zeros_like(base_distribution, dtype=float)
        hotspot_distribution[active] = 1.0 / len(active)
        return (
            (1.0 - self.hotspot_strength) * base_distribution
            + self.hotspot_strength * hotspot_distribution
        )

    def generate_spatiotemporal_attributes(self) -> None:
        """Jointly build time profiles and assign them to existing spatial nodes."""
        dynamic_count = int(self.n * self.dod)
        static_count = self.n - dynamic_count
        num_clusters = int(max(self.customer_city_map) + 1)
        city_map = np.asarray(self.customer_city_map, dtype=int)
        cluster_sizes = np.bincount(city_map, minlength=num_clusters)

        self.period_boundaries = np.linspace(
            0, self.release_horizon, self.spatial_period_count + 1
        )
        self.hotspot_schedule = self._resolve_hotspot_schedule(num_clusters)
        self.realized_burst_centers = (
            self._resolve_burst_centers(max(dynamic_count, 1))
            if self.temporal_mode != "uniform"
            else []
        )

        dynamic_releases = self._sample_release_times(dynamic_count, dynamic=True)
        static_latent_releases = self._sample_release_times(
            static_count, dynamic=False
        )
        profile_releases = np.concatenate(
            [dynamic_releases, static_latent_releases]
        )
        lead_times = self.rng.integers(
            self.lead_time_min, self.lead_time_max + 1, size=self.n
        )
        widths = self.rng.integers(
            self.tw_width_min, self.tw_width_max + 1, size=self.n
        )
        profile_starts = profile_releases + lead_times
        profile_ends = profile_starts + widths

        if np.any(profile_ends > self.horizon):
            raise RuntimeError(
                "Internal error: generated a time window beyond the horizon."
            )

        pools = []
        for cluster in range(num_clusters):
            pool = np.where(city_map == cluster)[0]
            self.rng.shuffle(pool)
            pools.append(list(int(x) for x in pool))

        base_distribution = cluster_sizes / cluster_sizes.sum()
        stationary_distribution = self._stationary_weights(cluster_sizes)

        self.tw_starts = np.zeros(self.n, dtype=int)
        self.tw_ends = np.zeros(self.n, dtype=int)
        self.available_times = np.zeros(self.n, dtype=int)
        self.latent_release_times = np.zeros(self.n, dtype=int)
        self.is_dynamic = np.zeros(self.n, dtype=bool)
        self.release_periods = np.full(self.n, -1, dtype=int)
        self.temporal_profile_ids = np.full(self.n, -1, dtype=int)
        self.types = np.asarray(
            [f"Synthetic-{self.temporal_mode}"] * self.n, dtype=object
        )

        capacity_fallback_count = 0
        dynamic_profile_order = np.argsort(dynamic_releases)
        for profile_id in dynamic_profile_order:
            release_time = int(profile_releases[profile_id])
            period = self._period_of(release_time)
            desired = self._cluster_distribution(
                period, base_distribution, stationary_distribution
            )

            available_mask = np.asarray([len(pool) > 0 for pool in pools])
            if self.spatial_mode == "time_varying":
                active_available = any(
                    len(pools[c]) > 0 for c in self.hotspot_schedule[period]
                )
                if not active_available and self.hotspot_strength > 0:
                    capacity_fallback_count += 1

            probabilities = desired * available_mask
            if probabilities.sum() <= 0:
                probabilities = base_distribution * available_mask
            if probabilities.sum() <= 0:
                raise RuntimeError("No unassigned customer remains for a dynamic profile.")
            probabilities = probabilities / probabilities.sum()

            cluster = int(self.rng.choice(num_clusters, p=probabilities))
            node = pools[cluster].pop()
            self._assign_profile(
                node=node,
                profile_id=int(profile_id),
                profile_releases=profile_releases,
                profile_starts=profile_starts,
                profile_ends=profile_ends,
                dynamic=True,
                period=period,
            )

        remaining_nodes = [node for pool in pools for node in pool]
        self.rng.shuffle(remaining_nodes)
        static_profile_ids = np.arange(dynamic_count, self.n, dtype=int)
        self.rng.shuffle(static_profile_ids)
        if len(remaining_nodes) != len(static_profile_ids):
            raise RuntimeError("Static-node and static-profile counts do not match.")

        for node, profile_id in zip(remaining_nodes, static_profile_ids):
            self._assign_profile(
                node=int(node),
                profile_id=int(profile_id),
                profile_releases=profile_releases,
                profile_starts=profile_starts,
                profile_ends=profile_ends,
                dynamic=False,
                period=-1,
            )

        self.capacity_fallback_count = int(capacity_fallback_count)
        self._validate_generated_instance(dynamic_count)
        self.generation_stats = self._build_generation_stats(
            cluster_sizes=cluster_sizes,
            city_map=city_map,
        )

        if self.verbose:
            print(json.dumps(self.generation_stats, ensure_ascii=False, indent=2))
            if num_clusters == 1 and self.spatial_mode == "time_varying":
                print(
                    "Warning: the base spatial generator produced only one cluster; "
                    "time-varying spatial hotspots are therefore not identifiable."
                )

    def _assign_profile(
        self,
        node: int,
        profile_id: int,
        profile_releases: np.ndarray,
        profile_starts: np.ndarray,
        profile_ends: np.ndarray,
        dynamic: bool,
        period: int,
    ) -> None:
        latent_release = int(profile_releases[profile_id])
        self.tw_starts[node] = int(profile_starts[profile_id])
        self.tw_ends[node] = int(profile_ends[profile_id])
        self.latent_release_times[node] = latent_release
        self.available_times[node] = latent_release if dynamic else 0
        self.is_dynamic[node] = bool(dynamic)
        self.release_periods[node] = int(period)
        self.temporal_profile_ids[node] = int(profile_id)

    def _validate_generated_instance(self, expected_dynamic_count: int) -> None:
        actual_dynamic_count = int(np.sum(self.is_dynamic))
        if actual_dynamic_count != expected_dynamic_count:
            raise RuntimeError(
                f"Expected {expected_dynamic_count} dynamic nodes, "
                f"generated {actual_dynamic_count}."
            )
        if np.any(self.tw_ends <= self.tw_starts):
            raise RuntimeError("Generated a non-positive time-window width.")
        if np.any(self.tw_ends > self.horizon):
            raise RuntimeError("Generated a time window beyond the horizon.")
        dynamic = self.is_dynamic
        if np.any(
            self.available_times[dynamic] + self.reaction_buffer
            > self.tw_starts[dynamic]
        ):
            raise RuntimeError("Reaction-buffer constraint is violated.")
        if np.any(self.available_times[dynamic] <= 0):
            raise RuntimeError("A dynamic customer has non-positive available_time.")
        if np.any(self.available_times[~dynamic] != 0):
            raise RuntimeError("A static customer has non-zero available_time.")

        customer_coords = np.asarray(self.coords, dtype=float)
        depot_coords = np.asarray(self.depots, dtype=float)
        if depot_coords.ndim != 2 or depot_coords.shape[0] == 0:
            raise RuntimeError("At least one depot is required for reachability checks.")
        depot_distances = np.linalg.norm(
            customer_coords[:, np.newaxis, :] - depot_coords[np.newaxis, :, :],
            axis=2,
        )
        self.min_depot_travel_times = np.ceil(
            np.min(depot_distances, axis=1) / self.feasibility_vehicle_speed
        ).astype(int)
        self.immediate_reachability_slacks = (
            np.asarray(self.tw_ends, dtype=int)
            - np.asarray(self.available_times, dtype=int)
            - self.min_depot_travel_times
        )
        unreachable = np.flatnonzero(self.immediate_reachability_slacks < 0)
        if len(unreachable):
            examples = []
            for node in unreachable[:5]:
                examples.append(
                    "customer_id={customer_id}: available_time={available_time}, "
                    "min_depot_travel={travel}, tw_end={tw_end}, "
                    "slack={slack}".format(
                        customer_id=int(node) + 1,
                        available_time=int(self.available_times[node]),
                        travel=int(self.min_depot_travel_times[node]),
                        tw_end=int(self.tw_ends[node]),
                        slack=int(self.immediate_reachability_slacks[node]),
                    )
                )
            suffix = "" if len(unreachable) <= 5 else "; ..."
            raise ImmediateReachabilityError(
                "Immediate-reachability constraint violated for "
                f"{len(unreachable)} customer(s): available_time + "
                "min_depot_travel <= tw_end. "
                + "; ".join(examples)
                + suffix
            )

    def _build_generation_stats(
        self, cluster_sizes: np.ndarray, city_map: np.ndarray
    ) -> dict:
        num_clusters = len(cluster_sizes)
        matrix = np.zeros(
            (self.spatial_period_count, num_clusters), dtype=int
        )
        for node in np.where(self.is_dynamic)[0]:
            matrix[self.release_periods[node], city_map[node]] += 1

        dynamic_by_cluster = matrix.sum(axis=0)
        release_by_period = matrix.sum(axis=1)
        hotspot_hits = []
        hotspot_lifts = []
        base_distribution = cluster_sizes / cluster_sizes.sum()
        for period in range(self.spatial_period_count):
            count = int(release_by_period[period])
            if self.spatial_mode == "time_varying":
                active = self.hotspot_schedule[period]
                hits = int(matrix[period, active].sum()) if count else 0
                share = hits / count if count else 0.0
                base_share = float(base_distribution[active].sum())
                lift = share / base_share if count and base_share > 0 else 0.0
                hotspot_hits.append(share)
                hotspot_lifts.append(lift)

        # The 30-minute width below is used only to aggregate audit statistics.
        # It does not constrain or align generated release times.
        release_statistics_bin_width = 30
        release_bin_edges = np.arange(
            0,
            self.release_horizon + release_statistics_bin_width + 1,
            release_statistics_bin_width,
        )
        dynamic_releases = self.available_times[self.is_dynamic]
        release_bin_counts = (
            np.histogram(dynamic_releases, bins=release_bin_edges)[0]
            if len(dynamic_releases)
            else np.zeros(len(release_bin_edges) - 1, dtype=int)
        )
        mean_bin_count = (
            float(np.mean(release_bin_counts))
            if len(release_bin_counts)
            else 0.0
        )
        fano = (
            float(np.var(release_bin_counts) / mean_bin_count)
            if mean_bin_count > 0
            else 0.0
        )

        dynamic_rates = np.divide(
            dynamic_by_cluster,
            cluster_sizes,
            out=np.zeros_like(dynamic_by_cluster, dtype=float),
            where=cluster_sizes > 0,
        )
        reaction_margins = (
            self.tw_starts[self.is_dynamic] - dynamic_releases
        )
        return {
            "dynamic_count": int(np.sum(self.is_dynamic)),
            "static_count": int(np.sum(~self.is_dynamic)),
            "cluster_node_counts": [int(x) for x in cluster_sizes],
            "cluster_dynamic_counts": [int(x) for x in dynamic_by_cluster],
            "cluster_dynamic_rates": [float(x) for x in dynamic_rates],
            "release_counts_by_period": [int(x) for x in release_by_period],
            "period_cluster_dynamic_counts": matrix.tolist(),
            "hotspot_share_by_period": (
                [float(x) for x in hotspot_hits]
                if self.spatial_mode == "time_varying"
                else None
            ),
            "hotspot_lift_by_period": (
                [float(x) for x in hotspot_lifts]
                if self.spatial_mode == "time_varying"
                else None
            ),
            "capacity_fallback_count": int(self.capacity_fallback_count),
            "release_statistics_bin_width": release_statistics_bin_width,
            "release_bin_counts": [int(x) for x in release_bin_counts],
            "release_bin_fano_factor": fano,
            "minimum_reaction_margin": (
                int(np.min(reaction_margins))
                if len(reaction_margins)
                else None
            ),
            "minimum_immediate_reachability_slack": int(
                np.min(self.immediate_reachability_slacks)
            ),
            "mean_immediate_reachability_slack": float(
                np.mean(self.immediate_reachability_slacks)
            ),
            "immediate_reachability_violation_count": int(
                np.sum(self.immediate_reachability_slacks < 0)
            ),
            "mean_time_window_width": float(
                np.mean(self.tw_ends - self.tw_starts)
            ),
        }

    def _generation_config(self) -> dict:
        return {
            "generator": "SpatioTemporalSVRPGenerator",
            "seed": self.seed,
            "temporal_mode": self.temporal_mode,
            "spatial_mode": self.spatial_mode,
            "horizon": self.horizon,
            "release_horizon": self.release_horizon,
            "reaction_buffer": self.reaction_buffer,
            "feasibility_vehicle_speed": self.feasibility_vehicle_speed,
            "immediate_reachability_constraint": (
                "available_time + min_depot_travel <= tw_end"
            ),
            "min_depot_travel_rounding": "ceil(euclidean_distance / vehicle_speed)",
            "lead_time_range": [self.lead_time_min, self.lead_time_max],
            "time_window_width_range": [
                self.tw_width_min,
                self.tw_width_max,
            ],
            "burst_centers": [int(x) for x in self.realized_burst_centers],
            "burst_count": len(self.realized_burst_centers),
            "burst_profile": self.burst_profile,
            "burst_parameter_source": self.burst_parameter_source,
            "burst_width": self.burst_width,
            "burst_width_sampling_range": (
                None
                if self.burst_width_sampling_range is None
                else [float(x) for x in self.burst_width_sampling_range]
            ),
            "burst_width_semantics": "gaussian_standard_deviation_minutes",
            "burst_widths": (
                [float(x) for x in self.realized_burst_widths]
                if self.realistic_calendar_profile
                else None
            ),
            "burst_strength": self.burst_strength,
            "burst_strength_sampling_range": (
                None
                if self.burst_strength_sampling_range is None
                else [float(x) for x in self.burst_strength_sampling_range]
            ),
            "uniform_background_share": 1.0 - self.burst_strength,
            "background_sampling": (
                "uniform_outside_peak_windows"
                if self.realistic_calendar_profile
                else "uniform_full_release_horizon"
            ),
            "burst_component_names": (
                self.realistic_peak_names
                if self.realistic_calendar_profile
                else None
            ),
            "burst_component_shares": (
                [float(x) for x in self.realized_burst_component_shares]
                if self.realistic_calendar_profile
                else None
            ),
            "burst_peak_windows": (
                [
                    [float(low), float(high)]
                    for low, high in self._scaled_realistic_peak_windows()
                ]
                if self.realistic_calendar_profile
                else None
            ),
            "burst_center_sampling_ranges": (
                [
                    [float(low), float(high)]
                    for low, high in self.realistic_center_ranges_reference
                ]
                if self.realistic_calendar_profile
                else None
            ),
            "burst_width_sampling_ranges": (
                [list(bounds) for bounds in self.realistic_width_sampling_ranges]
                if self.realistic_calendar_profile
                else None
            ),
            "burst_share_sampling_ranges": (
                [list(bounds) for bounds in self.realistic_share_sampling_ranges]
                if self.realistic_calendar_profile
                else None
            ),
            "realistic_calibration_targets": (
                {
                    "source": "Meituan-INFORMS operational food-delivery data",
                    "lunch_window_minutes": [645, 780],
                    "lunch_order_share": 0.2992,
                    "dinner_window_minutes": [1020, 1140],
                    "dinner_order_share": 0.2122,
                    "two_peak_window_share": 0.5114,
                    "max_30_minute_share": 0.0956,
                    "max_60_minute_share": 0.1702,
                    "peak_to_mean_15_minute_20h": 4.12,
                }
                if self.realistic_calendar_profile
                else None
            ),
            "spatial_period_count": self.spatial_period_count,
            "spatial_period_boundaries": [
                float(x) for x in self.period_boundaries
            ],
            "hotspot_strength": self.hotspot_strength,
            "hotspot_schedule": self.hotspot_schedule,
            "hotspot_schedule_policy": self.hotspot_schedule_policy,
            "hotspot_clusters_per_period": [
                len(active_clusters)
                for active_clusters in self.hotspot_schedule
            ],
            "stationary_cluster_weights": (
                None
                if self.stationary_cluster_weights is None
                else [float(x) for x in self.stationary_cluster_weights]
            ),
        }

    def save_dataset(self, filename: str) -> None:
        """Save the original JSON schema plus optional audit metadata."""
        parent = os.path.dirname(os.path.abspath(filename))
        os.makedirs(parent, exist_ok=True)

        dataset = {
            "name": (
                f"{self.n}_{self.depot_type}_depot_dod{int(self.dod * 100)}"
                f"_{self.temporal_mode}_{self.spatial_mode}"
            ),
            "num_vehicles": int(self.num_vehicles),
            "capacity": int(self.capacity),
            "depots": [
                {
                    "id": int(i),
                    "x": int(depot[0]),
                    "y": int(depot[1]),
                }
                for i, depot in enumerate(self.depots)
            ],
            "customers": [],
            "generation_config": self._generation_config(),
            "generation_stats": self.generation_stats,
        }

        city_map = np.asarray(self.customer_city_map, dtype=int)
        for i in range(self.n):
            dataset["customers"].append(
                {
                    "id": int(i + 1),
                    "x": int(self.coords[i][0]),
                    "y": int(self.coords[i][1]),
                    "demand": int(self.demands[i]),
                    "tw_start": int(self.tw_starts[i]),
                    "tw_end": int(self.tw_ends[i]),
                    "service_time": int(self.service_times[i]),
                    "is_dynamic": bool(self.is_dynamic[i]),
                    "available_time": int(self.available_times[i]),
                    "type": str(self.types[i]),
                    "cluster_id": int(city_map[i]),
                    "release_period": int(self.release_periods[i]),
                    "latent_release_time": int(self.latent_release_times[i]),
                    "temporal_profile_id": int(self.temporal_profile_ids[i]),
                }
            )

        with open(filename, "w", encoding="utf-8") as stream:
            json.dump(dataset, stream, ensure_ascii=False, indent=2)
        print(f"Dataset saved to {filename}")


def _parse_number_list(value: Optional[str], cast=float):
    if value is None or value.strip() == "":
        return None
    return [cast(item.strip()) for item in value.split(",") if item.strip()]


def _parse_hotspot_schedule(value: Optional[str]):
    if value is None or value.strip() == "":
        return None
    schedule = []
    for period in value.split(";"):
        clusters = [
            int(item.strip()) for item in period.split(",") if item.strip()
        ]
        if not clusters:
            raise argparse.ArgumentTypeError(
                "Every hotspot-schedule period must list at least one cluster."
            )
        schedule.append(clusters)
    return schedule


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a DVRP instance with uniform, strong-bursty, or "
            "reality-calibrated-bursty temporal arrivals and stationary/"
            "time-varying spatial cluster distributions."
        )
    )
    parser.add_argument("--scale", "--num-customers", dest="num_customers", type=int, default=100)
    parser.add_argument("--map-size", type=int, default=1000)
    parser.add_argument("--dod", type=float, default=0.5)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--depot-type", choices=["single", "multi"], default="single")
    parser.add_argument("--depot-placement", choices=["center", "random"], default="center")
    parser.add_argument("--service-time-mode", choices=["constant", "linear"], default="linear")
    parser.add_argument("--fixed-vehicle-num", type=int, default=200)
    parser.add_argument("--fixed-vehicle-capacity", type=int, default=500)
    parser.add_argument("--auto-fleet", action="store_true")

    parser.add_argument(
        "--temporal-mode",
        choices=["uniform", "bursty", "realistic_bursty"],
        default="uniform",
    )
    parser.add_argument(
        "--spatial-mode",
        choices=["stationary", "time_varying"],
        default="stationary",
    )
    parser.add_argument("--horizon", type=int, default=1440)
    parser.add_argument("--release-horizon", type=int, default=None)
    parser.add_argument("--reaction-buffer", type=int, default=30)
    parser.add_argument(
        "--vehicle-speed",
        type=float,
        default=5.0,
        help=(
            "Vehicle speed used by the immediate-reachability constraint; "
            "must match the simulation speed."
        ),
    )
    parser.add_argument("--lead-time-min", type=int, default=30)
    parser.add_argument("--lead-time-max", type=int, default=120)
    parser.add_argument("--tw-width-min", type=int, default=60)
    parser.add_argument("--tw-width-max", type=int, default=120)
    parser.add_argument(
        "--burst-count",
        type=int,
        default=None,
        help=(
            "Optional burst-center override. Defaults: bursty=4; "
            "realistic_bursty=two empirical lunch/dinner peaks."
        ),
    )
    parser.add_argument(
        "--burst-centers",
        type=str,
        default=None,
        help="Comma-separated release-time centers, e.g. 240,600,960.",
    )
    parser.add_argument(
        "--burst-width",
        type=float,
        default=None,
        help=(
            "Optional Gaussian standard deviation override. The bursty default "
            "is 15; realistic_bursty samples separate lunch/dinner widths."
        ),
    )
    parser.add_argument(
        "--burst-width-range",
        type=str,
        default=None,
        help="Optional instance-level Gaussian-width range as min,max.",
    )
    parser.add_argument(
        "--burst-strength",
        type=float,
        default=None,
        help=(
            "Optional burst-mixture override. The bursty default is 0.95; "
            "realistic_bursty samples empirical lunch/dinner window shares."
        ),
    )
    parser.add_argument(
        "--burst-strength-range",
        type=str,
        default=None,
        help="Optional instance-level burst-mixture range as min,max.",
    )

    parser.add_argument("--spatial-period-count", type=int, default=4)
    parser.add_argument("--hotspot-strength", type=float, default=0.80)
    parser.add_argument(
        "--hotspot-clusters-per-period",
        type=int,
        default=None,
        help=(
            "Optional fixed active-cluster count. By default, clusters are "
            "randomly and approximately evenly partitioned across periods."
        ),
    )
    parser.add_argument(
        "--hotspot-schedule",
        type=str,
        default=None,
        help=(
            "Semicolon-separated periods and comma-separated cluster IDs, "
            'e.g. "0;1;0,1;2".'
        ),
    )
    parser.add_argument(
        "--stationary-cluster-weights",
        type=str,
        default=None,
        help="Optional fixed cluster weights, e.g. 5,1,1.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="data_generation/dataset_spatiotemporal/example.json",
    )
    parser.add_argument("--verbose", action="store_true")
    return parser


def main() -> None:
    args = build_argument_parser().parse_args()
    fixed_vehicle_num = None if args.auto_fleet else args.fixed_vehicle_num
    fixed_vehicle_capacity = (
        None if args.auto_fleet else args.fixed_vehicle_capacity
    )

    generator = SpatioTemporalSVRPGenerator(
        num_customers=args.num_customers,
        map_size=args.map_size,
        dod=args.dod,
        fixed_vehicle_num=fixed_vehicle_num,
        fixed_vehicle_capacity=fixed_vehicle_capacity,
        depot_type=args.depot_type,
        depot_placement=args.depot_placement,
        service_time_mode=args.service_time_mode,
        seed=args.seed,
        verbose=args.verbose,
        temporal_mode=args.temporal_mode,
        spatial_mode=args.spatial_mode,
        horizon=args.horizon,
        release_horizon=args.release_horizon,
        reaction_buffer=args.reaction_buffer,
        feasibility_vehicle_speed=args.vehicle_speed,
        lead_time_min=args.lead_time_min,
        lead_time_max=args.lead_time_max,
        tw_width_min=args.tw_width_min,
        tw_width_max=args.tw_width_max,
        burst_count=args.burst_count,
        burst_centers=_parse_number_list(args.burst_centers, cast=int),
        burst_width=args.burst_width,
        burst_strength=args.burst_strength,
        burst_width_range=_parse_number_list(args.burst_width_range, cast=float),
        burst_strength_range=_parse_number_list(
            args.burst_strength_range, cast=float
        ),
        spatial_period_count=args.spatial_period_count,
        hotspot_strength=args.hotspot_strength,
        hotspot_clusters_per_period=args.hotspot_clusters_per_period,
        hotspot_schedule=_parse_hotspot_schedule(args.hotspot_schedule),
        stationary_cluster_weights=_parse_number_list(
            args.stationary_cluster_weights, cast=float
        ),
    )
    generator.generate_all()
    generator.save_dataset(args.output)
    print(json.dumps(generator.generation_stats, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
